server:
  port: 8095

spring:
  #数据库连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #使用dynamic-datasource框架
    dynamic:
      #设置默认数据源或者数据源组，read
      primary: read
      # 严格匹配数据源，默认false，true未匹配到指定数据源时抛异常，false使用默认数据源
      strict: false
      datasource:
        read:
          url: jdbc:mysql://localhost:3306/eraser?useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: passw@rd
          initial-size: 3
          min-idle: 1
          max-active: 20
          test-on-borrow: true
          driver-class-name: com.mysql.cj.jdbc.Driver
        write:
          url: jdbc:mysql://localhost:3306/ems-dev?useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: passw@rd
          initial-size: 3
          min-idle: 1
          max-active: 20
          test-on-borrow: true
          driver-class-name: com.mysql.cj.jdbc.Driver




